apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: qis-kv
  namespace: logstash
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "f99f6962-7808-4ff3-879a-e21bc2a2f3ee"
    keyvaultName: "kv-logstash-lab-3345"
    tenantId: "1658af60-3667-462c-8c0e-8ee391b6cab8"
    objects: |
      array:
        - |
          objectName: synapse-client-id
          objectType: secret
        - |
          objectName: synapse-client-secret
          objectType: secret
        - |
          objectName: es-cloud-id
          objectType: secret
        - |
          objectName: es-api-key
          objectType: secret
  secretObjects:
    - secretName: qis-synapse-sp
      type: Opaque
      data:
        - { objectName: synapse-client-id,     key: client-id }
        - { objectName: synapse-client-secret, key: client-secret }
    - secretName: es-playground
      type: Opaque
      data:
        - { objectName: es-cloud-id, key: cloud-id }
        - { objectName: es-api-key,  key: api-key }
